import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import "primereact/resources/themes/lara-light-indigo/theme.css";

//core
import "primereact/resources/primereact.min.css";

import Footer from "@/components/footer/page";
import Breadcrumbs from "@/components/breadcrumbs/Breadcrumbs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Borrow and Return System KDR Transport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`inter.className font-display`}>
        <div className="max-h-screen flex flex-row justify-start">
          <Navbar />
          <div className="p-4 bg-indigo-50 flex-col flex-1 overflow-scroll">
            <Breadcrumbs />
            <div className="bg-white py-6 px-3 sm:px-6 lg:px-8 rounded-lg mt-3 shadow-md h-full">
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
